// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpDGz5YRPuK1DjFtf2rwFOGMl4AluTafk',
    appId: '1:1057905423342:web:7e0e61afdf77877f9f94ff',
    messagingSenderId: '1057905423342',
    projectId: 'flutter-chat-app-bbe6f',
    authDomain: 'flutter-chat-app-bbe6f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bbe6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATG_4XZXrn2WGmPIcbAoG5FyfwWMczDC4',
    appId: '1:1057905423342:android:a501b2bfa6e793799f94ff',
    messagingSenderId: '1057905423342',
    projectId: 'flutter-chat-app-bbe6f',
    storageBucket: 'flutter-chat-app-bbe6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-9qGRrlYn3VJBZAOyL6kgny1ftlUQbvE',
    appId: '1:1057905423342:ios:afaacce7d3ecc0799f94ff',
    messagingSenderId: '1057905423342',
    projectId: 'flutter-chat-app-bbe6f',
    storageBucket: 'flutter-chat-app-bbe6f.appspot.com',
    iosClientId: '1057905423342-cvqc0jgbo2bdmvdad1f98gssjjl0584f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-9qGRrlYn3VJBZAOyL6kgny1ftlUQbvE',
    appId: '1:1057905423342:ios:9212938f4284a8b99f94ff',
    messagingSenderId: '1057905423342',
    projectId: 'flutter-chat-app-bbe6f',
    storageBucket: 'flutter-chat-app-bbe6f.appspot.com',
    iosClientId: '1057905423342-7puhjgmq9oquouo3slct0iu5ile0nurl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbee.RunnerTests',
  );
}
